// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNseOWjCqH-OFJKkYui1y1K3-2LmCSA_8',
    appId: '1:120492227199:android:43d59f50af331953e41d4a',
    messagingSenderId: '120492227199',
    projectId: 'medsync-c6d7e',
    storageBucket: 'medsync-c6d7e.firebasestorage.app',
    iosBundleId: 'com.example.medsyncc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNseOWjCqH-OFJKkYui1y1K3-2LmCSA_8',
    appId: '1:120492227199:ios:45d099b777c22462e41d4a',
    messagingSenderId: '120492227199',
    projectId: 'medsync-c6d7e',
    storageBucket: 'medsync-c6d7e.firebasestorage.app',
    iosBundleId: 'com.example.medsyncc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnv0r8aEEpvoJVZxsJTQ6Ff0NXwDRqFYc',
    appId: '1:120492227199:web:25a85428233915dce41d4a',
    messagingSenderId: '120492227199',
    projectId: 'medsync-c6d7e',
    authDomain: 'medsync-c6d7e.firebaseapp.com',
    storageBucket: 'medsync-c6d7e.firebasestorage.app',
    measurementId: 'G-VQKRLMBJRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU123ps4kOutLAaGunDhFJyt4yglB9AK8',
    appId: '1:120492227199:android:43d59f50af331953e41d4a',
    messagingSenderId: '120492227199',
    projectId: 'medsync-c6d7e',
    storageBucket: 'medsync-c6d7e.firebasestorage.app',
  );
}
